### ISSUE TITLE
Unable to set the local repo path. It keeps returning to the set repo pop up. 

### ISSUE THREAD

**Issue by BaaridunNasr** [appml/nano#6] opened 2019-05-12 05:49 UTC
The first time the app is installed, it asks to set the local repo path. When I press configure it takes me to the settings where the first option is to set local repo path.

I press the option and it takes me back to pop up.

I am running Android P Pixel Experience ROM.

**Comment by appml** [comment] 2019-05-12 09:17
Will be fixed in 3.0.1.  Thanks for reporting.

**Comment by BaaridunNasr** [comment] 2019-05-12 17:25
Thank you for following up!

**Comment by BaaridunNasr** [comment] 2019-05-17 03:04
![2019_05_17_08_29_45](https://user-images.githubusercontent.com/12585952/57900476-91de7b00-787e-11e9-8f5a-dfc5e20c96c1.gif)


Still having the same problem. Attaching a screen record.

**Comment by appml** [comment] 2019-05-17 08:08
That's expected behavior.  The app would not function without **Local Repo** specified under **Settings**.

Once a path is provided, the popup will disappear.

Hope this helps.

**Comment by BaaridunNasr** [comment] 2019-05-19 07:28
Yes, but I am not able to provide the path itself. Under settings the way to provide path is by pressing the Local Repository Path option, if I'm not mistaken. That itself sets it up in this loop of going to the start screen and asking me to configure it again...

**Comment by saelim** [comment] 2019-05-19 10:53
You should be able to set up the repo path or just accept the default.  Looks like you are using Pie or above.

**Closed as completed** 2019-05-19 11:49 UTC
